apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   kompose.cmd: kompose convert
  #   kompose.version: 1.24.0 (4a2a0458)
  # creationTimestamp: null
  name: backend
  labels:
    io.kompose.service: backend
spec:
  containers:
    - env:
        - name: TO_DO_DB
          valueFrom:
            configMapKeyRef:
              key: TO_DO_DB
              name: env-backend-env
      image: backend
      name: backend
      ports:
        - containerPort: 3001
      resources: {}
      volumeMounts:
        - mountPath: /app/node_modules
          name: backend-claim0
  restartPolicy: OnFailure
  volumes:
    - name: backend-claim0
      persistentVolumeClaim:
        claimName: backend-claim0
status: {}
