apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: client-claim0
  labels:
    io.kompose.service: client-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
